version: "3"
services:
  minio:
    image: minio/minio:edge@sha256:373cc16a29662f3f616a8de7facff0ef085257296256c59d64b158d9a59d2bd9
    environment:
      - MINIO_REGION_NAME=local
      - MINIO_ROOT_USER=test
      - MINIO_ROOT_PASSWORD=testdslocal
    ports:
      - 9000:9000
    command:
      - server
      - /data
  redis:
    image: redis:latest
    ports:
      - 6379:6379
